spring.application.name=lab4

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/shoe_product
spring.datasource.username=root
spring.datasource.password=0916395660Phuzzz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver